### PR TITLE
Add full list of accepted papers; sort in order of appearence on ICFP website; + bunch of links

### PR DESCRIPTION
**Pull request by ulysses4ever**

### CODE REVIEW

**Comment by gasche** [comment]
Thanks! I was thinking of doing the same.

**Comment by gasche** [comment]
Andreas Abel just published a draft of their paper online: http://www.cse.chalmers.se/~abela/publications.html#icfp20

Draft: <http://www.cse.chalmers.se/~abela/icfp20.pdf>

Extended version: <http://www.cse.chalmers.se/~abela/icfp20-long.pdf>

**Comment by llelf** [comment]
@ulysses4ever @gasche thanks! added.

**Comment by ulysses4ever** [comment]
Thanks Gabriel! Thanks Antonio!

**Pull request merged**
